teleop_twist_joy:
  ros__parameters:
    axis_linear: 1      # analógico esquerdo vertical
    scale_linear: 0.3
    scale_linear_turbo: 0.6

    axis_angular: 0     # analógico esquerdo horizontal
    scale_angular: 1.5
    scale_angular_turbo: 2.5

    enable_button: 4    # L1
    enable_turbo_button: 5  # R1

    require_enable_button: true
